### PR TITLE
(#4) Fix flowable not desubscribing correctly from the store when disposed

### LINKED ISSUE #4: Multiple publish processor per Store
Calling to `flowable` store's extension create a new `PublishProcessor` each time. 

Shouldn't the extension provide an unique instance for each Store?

This is a big problem on doing one shots operations, despite of `takeUntil` Rx`s operator store keep hold each listener.

### PR DESCRIPTION
**Pull request by adriangl**
Should fix #4 
Basically backports [minikorp/mini fix](https://github.com/minikorp/mini/issues/7) for this and adds tests to ensure that subscriptions are, in fact properly closed for both `flowable()` and `observable()` extension functions.

Also, `flowable()` now accepts a backpressure strategy. I set up ~`LATEST`~ `BUFFER` as the default as it seems the most sensible to me. Feel free to discuss this ;)

### CODE REVIEW

File: mini-rx2/src/main/java/mini/rx/RxUtils.kt [hunk 1]
```diff
@@ -57,20 +57,18 @@ class DefaultSubscriptionTracker : SubscriptionTracker {
...
     val subject = PublishSubject.create<S>()
     val subscription = subscribe(hotStart = false) {
         subject.onNext(it)
     }
-    return subject.doOnTerminate { subscription.close() }
+    return subject
+        .doOnDispose { subscription.close() }
+        .doOnTerminate { subscription.close() }
         .let { if (hotStart) it.startWith(state) else it }
+}
```
Comment (danielceinos) [inline mini-rx2/src/main/java/mini/rx/RxUtils.kt]: I'll add test for `observable` extension too

Comment (adriangl) [reply mini-rx2/src/main/java/mini/rx/RxUtils.kt]: It's already there 😛

**Comment by adriangl** [comment]
Minor change, I change the default strategy to `BUFFER` since it seems the safest solution to ensure that all items are processed (though OoM might happen, but it will be up to the user to see if they need to change the backpressure strategy if they need it for their use case)
